version: "3"

services:
  prometheus:
    image: prom/prometheus

  pushgateway:
    image: prom/pushgateway

  weather-api:
    build: .
    ports:
    - 8080:80

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.server.name
      - GF_SECURITY_ADMIN_PASSWORD=secret