{
 "title": "Heating",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  { "title": "Room temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kuchyna",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "temperature{termostat='Kuchyna'}"
    }
   ]
  },
  {
   "title": "Obyvacka",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "temperature{termostat='Obyvacka'}"
    }
   ]
  },
  {
   "title": "Kupelna",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "temperature{termostat='Kupelna'}"
    }
   ]
  },
  { "title": "Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "HEATING in Kuchyna",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(heat{termostat=\"Kuchyna\"}[$__range])/60"
    }
   ]
  },
  {
   "title": "HEATING in Kupelna",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(heat{termostat=\"Kupelna\"}[$__range])/60"
    }
   ]
  },
  {
   "title": "Consumption - kWh",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "expr": "(0.5*(sum_over_time(heat{termostat=\"Kupelna\"}[$__range])/60)) + ((sum_over_time(heat{termostat=\"Kupelna\"}[$__range])/60 + sum_over_time(heat{termostat=\"Kupelna\"}[$__range])/60)*2.736/2)"
    }
   ]
  },
  {
   "title": "Consumption - Euro",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "expr": "((0.5*(sum_over_time(heat{termostat=\"Kupelna\"}[$__range])/60)) + ((sum_over_time(heat{termostat=\"Kupelna\"}[$__range])/60 + sum_over_time(heat{termostat=\"Kupelna\"}[$__range])/60)*2.736/2))*0.16"
    }
   ]
  },
  {
   "title": "HEATING in Obyvacka",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(heat{termostat=\"Obyvacka\"}[$__range])/60"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Chalupa heating",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "heat" }
   ]
  },
  {
   "title": "Chalupa temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "Consumption - kWh",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    { "expr": "sum(rate(heat[1d]))" }
   ]
  }
 ]
}